### ISSUE TITLE
Removing database columns results in inability to restore/reify.

### ISSUE THREAD

**Issue by commuun** [westonganger/active_snapshot#58]
When a database column is removed, restoring or reifying existing items that still reference that column will result in an "unknown attribute" error.

For instance I removed the price field from my products table and tried to reify an old snapshot:

```ruby
> Product.find(1234).snapshots.last.fetch_reified_items
ActiveModel::UnknownAttributeError: unknown attribute 'price' for Product.
```

This happens in both `Snapshot#fetch_reified_items` and `SnapshotItem#restore_item!`

I'm not sure what the best solution would be.

* Attack it at the source (`SnapshotItem#object`) and remove all fields that are no longer present in (in this example) `Product.attribute_names`, which would fix both cases
* Filter it out in `Snapshot#fetch_reified_items` and `SnapshotItem#restore_item!` individually so that #object stays "pure"

**Comment by westonganger** [comment]
I think that `Snapshot#fetch_reified_items` and `SnapshotItem#restore_item!` would be the place to put it.

**Comment by westonganger** [comment]
Would appreciate a PR for this.

**Comment by dmrAnderson** [comment]
@westonganger 
Would you like some help with that? Do you already know how to do it effectively?

**Comment by westonganger** [comment]
@dmrAnderson yes

**Comment by westonganger** [comment]
This is tough

I dont want this gem to silently ignore this issue. When this issue is encountered this it means that you have made a breaking change to your backup and restore system.

But we also need restore to continue to work after this situation.

Just need to figure our what the best way to notify the developer when this situation is encountered. Some ideas:

- Readme section to describe this issue, basically state "you have been warned"
- Log a warning
- Raise exception (the longer I think about this the worse this solution feels, I want to notify the developer before they break it...)
- Silently ignore

**Comment by westonganger** [comment]
I've added https://github.com/westonganger/active_snapshot/pull/66 which looks to solve this.

Took the approach of readme updates and silently ignoring the data.

**Comment by westonganger** [comment]
v0.5.1 is now released which contains the changes which now ignores data which cannot be assigned to the model instance
